services:
  web:
    container_name: web
    image: web
    build:
      context: web
    ports:
      - "8080:3000"
    networks:
      - app

  storage:
    container_name: storage
    image: storage
    build:
      context: storage
    ports:
      - "8081:8080"
    networks:
      - app

  search:
    container_name: search
    image: search
    build:
      context: search
    ports:
      - "8082:8080"
    networks:
      - app

  ocr:
    container_name: ocr
    image: ocr
    build:
      context: ocr
    ports:
      - "8083:5000"
    networks:
      - app

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dms
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"

networks:
  app:
    driver: bridge
