spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/dms
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework: INFO
server.port: 8085